/******************************************************************************

    ATPGK - An automated test pattern generator for integrated circuit

    Copyright (C) 2023-2024 Hugo Brisset & Gabriel Levy

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or 
    any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.

    Contact: hugo.brisset@proton.me / gabriel.levy@skiff.com

******************************************************************************/

/**
 * @file YosysCell.hpp
 * @brief Definition of the YosysCell class
*/

#pragma once

#include "../Cell.hpp"

/**
 * @class YosysCell
 * @brief Class that represents a cell in the circuit generated by the Yosys synthesis software.
 * 
 * The YosysCell class is derived from the Cell class and represents a more specific type of node in a circuit.
 */

class YosysCell : public Cell {
public:
    /**
     * @brief Constructor for the YosysCell class.
     *
     * Constructs a YosysCell with a unique identifier. Calls the constructor of the Cell base class.
     * @param identifier An integer uniquely identifying the cell, passed to the base Node constructor.
     * @param netlistName The name of the gate in the netlist
     */
    YosysCell(size_t identifier, std::string netlistName);
};